# Generated by Django 2.1.8 on 2019-05-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0003_auto_20190531_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedVideo',
        ),
    ]
