# Generated by Django 2.1.8 on 2019-06-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0005_video_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.BooleanField()),
                ('queries', models.ForeignKey(on_delete=None, to='Player.Query')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='query',
        ),
        migrations.AddField(
            model_name='throughmodel',
            name='videos',
            field=models.ForeignKey(on_delete=None, to='Player.Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='query',
            field=models.ManyToManyField(blank=True, to='Player.Query'),
        ),
    ]
